import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";

const root = process.cwd();
const packageJson = await readJson(path.join(root, "package.json"));
const isTemplatePackage = packageJson?.name === "crewup-harness";
const scripts = packageJson?.scripts ?? {};
const bin = packageJson?.bin ?? {};
const lockfile = detectLockfile();
const git = gitInfo();

const projectChecks = [
  ["package.json", existsSync(path.join(root, "package.json")), "required project manifest"],
  [".harness/", existsSync(path.join(root, ".harness")), "workflow core directory"],
  ["README.md", existsSync(path.join(root, "README.md")), "project or package documentation"],
  ["AGENTS.md", existsSync(path.join(root, "AGENTS.md")), "repository-level agent entry"],
  [".git/", existsSync(path.join(root, ".git")), "git repository"],
  ["node_modules/", existsSync(path.join(root, "node_modules")), "dependencies installed"],
  ["lockfile", Boolean(lockfile), lockfile || "package-lock.json / pnpm-lock.yaml / yarn.lock"]
];

const cliChecks = [
  ["crewup bin", normalizeBinPath(bin.crewup) === "bin/crewup.mjs", "package bin points to bin/crewup.mjs"],
  ["doctor script", Boolean(scripts["harness:doctor"]), "npm script is available"],
  ["check script", Boolean(scripts["harness:check"]), "npm script is available"],
  ["inspect script", Boolean(scripts["harness:inspect"]), "npm script is available"],
  ["init script", Boolean(scripts["harness:init"]), "npm script is available"],
  ["run script", Boolean(scripts["harness:run"]), "npm script is available"],
  ["finish script", Boolean(scripts["harness:finish"] || scripts["harness:finalize"]), "finish/finalize entry is available"],
  ["agent adapter", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "agent.yaml")), "selected agent environment is recorded"],
  ["workspace profile", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "profile.yaml")), "generated by crewup init in target projects"],
  ["workspace overlay", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "overlay.yaml")), "generated by crewup init in target projects"]
];

const envChecks = [
  ["node", process.version, "runtime version"],
  ["package manager", lockfile || "missing", "detected from lockfile"],
  ["git branch", git.branch || "unknown", "current branch"],
  ["git status", git.dirty ? "dirty" : "clean", "working tree status"],
  ["OPENAI_API_KEY", process.env.OPENAI_API_KEY ? "set" : "not set", "required only for SDK/API mode"]
];

const lines = [
  "# CrewUp Doctor",
  "",
  "## Project",
  "",
  "| Check | Status | Note |",
  "| --- | --- | --- |",
  ...projectChecks.map(row),
  "",
  "## CLI",
  "",
  "| Check | Status | Note |",
  "| --- | --- | --- |",
  ...cliChecks.map(row),
  "",
  "## Environment",
  "",
  "| Item | Value | Note |",
  "| --- | --- | --- |",
  ...envChecks.map(([name, value, note]) => `| ${name} | ${value} | ${note} |`),
  "",
  "## Recommendations",
  "",
  ...recommendations()
];

console.log(lines.join("\n"));

function row([name, ok, note]) {
  return `| ${name} | ${ok ? "ok" : "missing"} | ${note} |`;
}

function recommendations() {
  const items = [];
  if (!existsSync(path.join(root, ".harness"))) {
    items.push("- Run `npx crewup install`.");
    return items;
  }
  if (isTemplatePackage) {
    items.push("- This repository is the CrewUp template package; `.harness/project/` is generated inside target projects by `crewup init`.");
    items.push("- Before publishing, run `npm run harness:check` and `npm pack --dry-run`.");
  } else {
    if (!existsSync(path.join(root, ".harness", "project", "profile.yaml")) || !existsSync(path.join(root, ".harness", "project", "overlay.yaml"))) {
      items.push("- Run `npx crewup inspect --no-ai` and `npx crewup init --force`.");
    }
    if (!scripts.test) items.push("- No `test` script found. Verification will rely on generic checks until one is added.");
    if (!scripts.build) items.push("- No `build` script found. Build verification will be skipped unless project policy provides another command.");
    items.push("- Daily flow: `npx crewup run \"...\"` then `npx crewup finish <run-id>`.");
  }
  if (!process.env.OPENAI_API_KEY) {
    items.push("- `OPENAI_API_KEY` is not set. This is fine for static mode, but `inspect --ai` and SDK orchestration need it.");
  }
  return items.length ? items : ["- No immediate action needed."];
}

function detectLockfile() {
  if (existsSync(path.join(root, "package-lock.json"))) return "package-lock.json";
  if (existsSync(path.join(root, "pnpm-lock.yaml"))) return "pnpm-lock.yaml";
  if (existsSync(path.join(root, "yarn.lock"))) return "yarn.lock";
  return "";
}

function normalizeBinPath(value) {
  return String(value ?? "").replaceAll("\\", "/").replace(/^\.\//, "");
}

function gitInfo() {
  const branch = spawnSync("git", ["branch", "--show-current"], { cwd: root, encoding: "utf8" });
  const status = spawnSync("git", ["status", "--porcelain"], { cwd: root, encoding: "utf8" });
  return {
    branch: branch.status === 0 ? branch.stdout.trim() : "",
    dirty: status.status === 0 ? Boolean(status.stdout.trim()) : false
  };
}

async function readJson(target) {
  if (!existsSync(target)) return null;
  try {
    return JSON.parse((await readFile(target, "utf8")).replace(/^\uFEFF/, ""));
  } catch {
    return null;
  }
}
