import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { verifyCoreLock } from "./lib/core-lock.mjs";
import { detectTerminalEncoding, encodingHelpText, encodingProfileText } from "./lib/terminal-encoding.mjs";

const root = process.cwd();
const args = process.argv.slice(2);

if (args.includes("--encoding-help")) {
  console.log(encodingHelpText());
  process.exit(0);
}

if (args.includes("--encoding-profile")) {
  console.log(encodingProfileText());
  process.exit(0);
}

const packageJson = await readJson(path.join(root, "package.json"));
const isTemplatePackage = packageJson?.name === "crewup-harness";
const scripts = packageJson?.scripts ?? {};
const bin = packageJson?.bin ?? {};
const lockfile = detectLockfile();
const git = gitInfo();
const integrations = await readIntegrations();
const terminalEncoding = detectTerminalEncoding({ cwd: root });
const coreLock = existsSync(path.join(root, ".harness")) ? await verifyCoreLock(root) : null;

const projectChecks = [
  ["package.json", existsSync(path.join(root, "package.json")), "required project manifest"],
  [".harness/", existsSync(path.join(root, ".harness")), "workflow core directory"],
  ["README.md", existsSync(path.join(root, "README.md")), "project or package documentation"],
  ["AGENTS.md", existsSync(path.join(root, "AGENTS.md")), "repository-level agent entry"],
  [".git/", existsSync(path.join(root, ".git")), "git repository"],
  ["node_modules/", existsSync(path.join(root, "node_modules")), "dependencies installed"],
  ["lockfile", Boolean(lockfile), lockfile || "package-lock.json / pnpm-lock.yaml / yarn.lock"]
];

const cliChecks = [
  ["crewup bin", normalizeBinPath(bin.crewup) === "bin/crewup.mjs", "package bin points to bin/crewup.mjs"],
  ["doctor script", Boolean(scripts["harness:doctor"]), "npm script is available"],
  ["check script", Boolean(scripts["harness:check"]), "npm script is available"],
  ["inspect script", Boolean(scripts["harness:inspect"]), "npm script is available"],
  ["init script", Boolean(scripts["harness:init"]), "npm script is available"],
  ["run script", Boolean(scripts["harness:run"]), "npm script is available"],
  ["finish script", Boolean(scripts["harness:finish"]), "finish entry is available"],
  ["agent adapter", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "agent.yaml")), "selected agent environment is recorded"],
  ["workspace profile", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "profile.yaml")), "generated by crewup init in target projects"],
  ["workspace overlay", isTemplatePackage || existsSync(path.join(root, ".harness", "project", "overlay.yaml")), "generated by crewup init in target projects"]
  ,
  ["sealed core", isTemplatePackage || coreLock?.ok === true, coreLockStatusNote()]
];

const envChecks = [
  ["node", process.version, "runtime version"],
  ["package manager", lockfile || "missing", "detected from lockfile"],
  ["git branch", git.branch || "unknown", "current branch"],
  ["git status", git.dirty ? "dirty" : "clean", "working tree status"],
  ["terminal encoding", terminalEncoding.value, terminalEncoding.note],
  ["OPENAI_API_KEY", process.env.OPENAI_API_KEY ? "set" : "not set", "required only for SDK/API mode"]
];

const lines = [
  "# CrewUp Doctor",
  "",
  "## Project",
  "",
  "| Check | Status | Note |",
  "| --- | --- | --- |",
  ...projectChecks.map(row),
  "",
  "## CLI",
  "",
  "| Check | Status | Note |",
  "| --- | --- | --- |",
  ...cliChecks.map(row),
  "",
  "## Environment",
  "",
  "| Item | Value | Note |",
  "| --- | --- | --- |",
  ...envChecks.map(([name, value, note]) => `| ${name} | ${value} | ${note} |`),
  "",
  "## Optional Integrations",
  "",
  "| Integration | Provider | Enabled | Detected | Note |",
  "| --- | --- | --- | --- | --- |",
  ...integrationRows(),
  "",
  "## Recommendations",
  "",
  ...recommendations()
];

console.log(lines.join("\n"));

function row([name, ok, note]) {
  return `| ${name} | ${ok ? "ok" : "missing"} | ${note} |`;
}

function recommendations() {
  const items = [];
  if (!existsSync(path.join(root, ".harness"))) {
    items.push("- Run `npx crewup install`.");
    return items;
  }
  if (isTemplatePackage) {
    items.push("- This repository is the CrewUp template package; `.harness/project/` is generated inside target projects by `crewup init`.");
    items.push("- Before publishing, run `npm run harness:check` and `npm pack --dry-run`.");
  } else {
    if (!existsSync(path.join(root, ".harness", "project", "profile.yaml")) || !existsSync(path.join(root, ".harness", "project", "overlay.yaml"))) {
      items.push("- Run `npx crewup inspect --no-ai` and `npx crewup init --force`.");
    }
    if (!scripts.test) items.push("- No `test` script found. Verification will rely on generic checks until one is added.");
    if (!scripts.build) items.push("- No `build` script found. Build verification will be skipped unless project policy provides another command.");
    items.push("- Daily flow: `npx crewup run \"...\"` then `npx crewup finish <run-id>`.");
  }
  if (!process.env.OPENAI_API_KEY) {
    items.push("- `OPENAI_API_KEY` is not set. This is fine for static mode, but `inspect --ai` and SDK orchestration need it.");
  }
  if (terminalEncoding.warning) {
    items.push(`- ${terminalEncoding.warning}`);
  }
  if (integrations.length > 0) {
    items.push("- Optional integrations are never required for the default CrewUp workflow. Use `npx crewup integrations status` for details.");
  }
  if (coreLock && !coreLock.ok && !isTemplatePackage) {
    items.push("- CrewUp core drift detected. Run `npx crewup install --force` to restore installed core files before using project runs.");
  }
  return items.length ? items : ["- No immediate action needed."];
}

function coreLockStatusNote() {
  if (isTemplatePackage) return "source package does not require installed core lock";
  if (!coreLock) return "install CrewUp first";
  if (coreLock.ok) return `${coreLock.lock?.files?.length ?? 0} sealed core files verified`;
  return coreLock.problems[0] ?? "sealed core verification failed";
}

function integrationRows() {
  if (integrations.length === 0) return ["| none | - | no | no | no integrations configured |"];
  return integrations.map((item) => {
    const detected = detectCommand(item.detect);
    return `| ${item.id} | ${item.provider} | ${item.enabled ? "yes" : "no"} | ${detected.ok ? "yes" : "no"} | ${detected.note} |`;
  });
}

async function readIntegrations() {
  const target = path.join(root, ".harness", "config", "integrations.yaml");
  if (!existsSync(target)) return [];
  try {
    const parsed = parseYaml(await readFile(target, "utf8"))?.integrations ?? {};
    return Object.entries(parsed).map(([id, value]) => ({
      id,
      provider: value?.provider ?? "-",
      enabled: Boolean(value?.enabled),
      detect: value?.commands?.detect ?? ""
    }));
  } catch {
    return [];
  }
}

function detectCommand(commandText) {
  const parts = splitCommand(commandText);
  if (!parts.length) return { ok: false, note: "no detect command" };
  const result = runCommand(parts);
  if (result.status === 0) return { ok: true, note: firstLine(result.stdout || result.stderr) || "available" };
  return { ok: false, note: "optional provider not found" };
}

function splitCommand(commandText) {
  return String(commandText ?? "").match(/"[^"]+"|'[^']+'|\S+/g)?.map((part) => part.replace(/^["']|["']$/g, "")) ?? [];
}

function firstLine(text) {
  return String(text ?? "").trim().split(/\r?\n/).find(Boolean) ?? "";
}

function runCommand(parts) {
  if (process.platform !== "win32") {
    return spawnSync(parts[0], parts.slice(1), { cwd: root, encoding: "utf8" });
  }
  return spawnSync(parts.map(quoteShellArg).join(" "), {
    cwd: root,
    encoding: "utf8",
    shell: true
  });
}

function quoteShellArg(value) {
  const text = String(value);
  if (/^[A-Za-z0-9._~:/\\-]+$/.test(text)) return text;
  return `"${text.replaceAll('"', '\\"')}"`;
}

function detectLockfile() {
  if (existsSync(path.join(root, "package-lock.json"))) return "package-lock.json";
  if (existsSync(path.join(root, "pnpm-lock.yaml"))) return "pnpm-lock.yaml";
  if (existsSync(path.join(root, "yarn.lock"))) return "yarn.lock";
  return "";
}

function normalizeBinPath(value) {
  return String(value ?? "").replaceAll("\\", "/").replace(/^\.\//, "");
}

function gitInfo() {
  const branch = spawnSync("git", ["branch", "--show-current"], { cwd: root, encoding: "utf8" });
  const status = spawnSync("git", ["status", "--porcelain"], { cwd: root, encoding: "utf8" });
  return {
    branch: branch.status === 0 ? branch.stdout.trim() : "",
    dirty: status.status === 0 ? Boolean(status.stdout.trim()) : false
  };
}

async function readJson(target) {
  if (!existsSync(target)) return null;
  try {
    return JSON.parse((await readFile(target, "utf8")).replace(/^\uFEFF/, ""));
  } catch {
    return null;
  }
}
